name: C/C++ CI

on: [push]

jobs:
  build:
    env: 
      super_secret: ${{ secrets.SeverName }}
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: main
      run: main.cpp
